ci:  completely change github action
I gave up with the previous script. This should make it!

...

Hopefully.

diff --git a/.github/workflows/host_docs.yaml b/.github/workflows/host_docs.yaml
--- a/.github/workflows/host_docs.yaml
+++ b/.github/workflows/host_docs.yaml
@@ -1,44 +1,26 @@
-name: Build-sphinx-docs
-
-# Controls when the workflow will run
+name: "Pull Request Docs Check"
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
-  push:
-    branches: [ main ]
+- pull_request
+- workflow_dispatch
 
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs: 
-  # This workflow contains a single job called "build"
-  build: 
-    # The type of runner that the job will run on
+jobs:
+  docs:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v2
-        with:
-           python-version: "3.10"
-        
-      - name: Install dependencies
-        run: | 
-          python -m pip install --upgrade pip
-          python -m pip install -U sphinx
-          python -m pip install sphinx-rtd-theme
-          python -m pip install sphinx-autoapi
-          python -m pip install myst_parser
-          python -m pip install furo
-          python -m pip install ghp-import==2.1.0
-      - name: Build HTML
-        run: | 
-          cd docs/
-          make html
-      - name: Run ghp-import
-        run: | 
-          ghp-import -n -p -f docs/build/html
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/kennylajara/WML.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
